### ISSUE TITLE
Missing post-installation commands

### ISSUE THREAD

**Issue by vlahanas** [awslabs/elastic-beanstalk-docs#30]
Hello,

this documentation is missing an important part of Symfony deployments, which are the post installation commands for warming up the cache, removing app_dev.php (if required) and checking that the server is properly configured (php bin/console doctrine:ensure-production-settings --env=prod).

When and how should these post-installation steps be performed?

**Comment by mwunderl** [comment]
Hi vlahanas,

Sorry about the delayed response. I'm not very familiar with Symfony. Can you provide more information about the commands that need to be run and how to check configuration?

You can use configuration files to run commands during deployments [1]. To remove a file, delete it from your source code, commit, and then redeploy. To run a command on an instance once without deploying, connect to it over ssh with the **eb ssh** command or by following the instructions in the guide [2].
[1] [Customizing Software on Linux Servers](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/customize-containers-ec2.html)
[2] [Listing and Connecting to Server Instances](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.ec2connect.html)

**Comment by vlahanas** [comment]
Also delayed response, sorry about that,

Symfony provides a number of commands for the execution of post-installation actions, allowing to properly "initialize" your setup. The most commonly used are:

1. Database update
php bin/console doctrine:schema:update 

2. Checking that the environment is properly configured for production
php bin/console doctrine:ensure-production-settings --env=prod

3. Clearing and warming up the cache
php bin/console cache:clear --env=prod

These commands can be performed in the .config file, but the catch is that one of them might fail, if for instance you need to connect to an RDS database (command no1) and during the initial EB deployment, you have not properly set the connection info. Then, the whole deployment fails and you end up with a degraded environment status, trying to figure out what the problem. 

I am currently performing these commands inside a "post-install-cmd" block at the composer file, and some extra commands using ssh as you said. But the average (or bellow-average, as i am 😄 ) user would be grateful if this complete deployment process was described in the documentation!
