### ISSUE TITLE
Service:AmazonCloudFormation, Message:Template format error: Unresolved resource dependencies [fs-****] in the Resources block of the template

### ISSUE THREAD

**Issue by drbago** [awslabs/elastic-beanstalk-docs#46]
Using the example [storage-efs-mountfilesystem.config](https://github.com/awslabs/elastic-beanstalk-docs/blob/master/configuration-files/aws-provided/instance-configuration/storage-efs-mountfilesystem.config#L33) to mount EFS on EB, I experience this error:

> Service:AmazonCloudFormation, Message:Template format error: Unresolved resource dependencies [fs-****] in the Resources block of the template

After reading about the same error in [this forum thread](https://forums.aws.amazon.com/thread.jspa?threadID=245881), I tried changing the original FILE_SYSTEM_ID format...

>     FILE_SYSTEM_ID: '`{"Ref" : "fs-****"}`'

to match the example in the thread...

>     FILE_SYSTEM_ID: fs-****

Which works successfully.

Is it possible that the example is incorrect?  The [load-balanced Wordpress on EB example](https://github.com/awslabs/eb-php-wordpress/blob/master/.ebextensions/efs-mount.config#L12) also seems to have this issue.

**Comment by dankhen** [comment]
It looks like the example is correct, and at the same time there is a legitimate case when it would fail.  There is actually a comment in [storage-efs-mountfilesystem.config](https://github.com/awslabs/elastic-beanstalk-docs/blob/master/configuration-files/aws-provided/instance-configuration/storage-efs-mountfilesystem.config#L33) that explains it:
```
#### The FILE_SYSTEM_ID setting references a resource named "FileSystem", which is created by the
#### storage-efs-createfilesystem.config configuration file. To use this file to mount a
#### file system that you created outside of AWS Elastic Beanstalk, replace the Ref with the
#### resource ID (e.g., fs-e7605f4e):
####
####      FILE_SYSTEM_ID: fs-e7605f4e
```
What this means is that in order for the example to work as-is, you have to also use `storage-efs-createfilesystem.config`. If you don't, and you want to use an EFS resource created another way (e.g. outside of Beanstalk), you have to replace the resource ID as you did.

I hope this makes sense!

**Comment by drbago** [comment]
That makes sense.  This issue as I described is invalid.  I just did not read the comments carefully enough.
