### ISSUE TITLE
Using the default KmsKey value in storage-efs-createfilesystem.config causes deployment to fail

### ISSUE THREAD

**Issue by alnorth** [awslabs/elastic-beanstalk-docs#55]
I used `Encrypted: "false"` and `KmsKey: ""` and got the validation message below:

> 1 validation error detected: Value '' at 'kmsKeyId' failed to satisfy constraint: Member must have length greater than or equal to 1

This prevented the creation of the filesystem. When I removed the `Encrypted` and `KmsKeyId` sections from the `FileSystem` properties then the deployment worked fine. However, these were below the line stating "Do not modify values below this line".

**Comment by dankhen** [comment]
Looking into this.

**Comment by dankhen** [comment]
Hello again,
We have a bug in this config file. EFS requires KmsKeyId to be >=1 characters in length, or not set at all. Not setting it at all would be tricky, since we use an indirect reference in this example. I will work on an improvement. Thanks for pointing it out!

**Comment by dankhen** [comment]
Pushed an improved version. Works out of the box for non-encrypted EFS, and has modified instructions for encrypted EFS. Thanks!
