### ISSUE TITLE
EFS_DNS_NAME undefined

### ISSUE THREAD

**Issue by karliszigurs** [awslabs/elastic-beanstalk-docs#57]
https://github.com/awslabs/elastic-beanstalk-docs/blob/4772c9da53ce2b7ef9604031f810d2fc14f00cba/configuration-files/aws-provided/instance-configuration/storage-efs-mountfilesystem.config#L60

In the example script provided it is unclear where from the EFS_DNS_NAME should come from

**Comment by dankhen** [comment]
It is indeed strange, mainly from the perspective that in the example, EFS_DNS_NAME isn't used at all (other than in that echo line you pointed to).

We have a new version of this example in the works, so I am not going to change it at this point. Thanks for drawing our attention to it.
